apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-juice-shop
  namespace: my-juice-shop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecAuditLog /var/log/modsec_audit.log
spec:
  tls:
  - hosts:
    - my-juice-shop.local
    secretName: my-juice-shop-tls
  rules:
  - host: my-juice-shop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-juice-shop
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-juice-shop
  namespace: my-juice-shop
  labels:
    app: my-juice-shop
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: my-juice-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-juice-shop
  namespace: my-juice-shop
spec:
  selector:
    matchLabels:
      app: my-juice-shop
  template:
    metadata:
      labels:
        app: my-juice-shop
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions: [{ key: app, operator: In, values: [my-juice-shop] }]
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: my-juice-shop
          image: "docker.io/bkimminich/juice-shop:v12.7.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 256Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-juice-shop
  namespace: my-juice-shop
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-juice-shop
  targetCPUUtilizationPercentage: 80